# Generated by Django 5.2.4 on 2025-07-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_type', models.CharField(choices=[('flood', 'Flood'), ('drought', 'Drought'), ('storm', 'Storm'), ('pest', 'Pest Attack'), ('disease', 'Crop Disease'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('date_occurred', models.DateField()),
                ('estimated_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date_reported'],
                'permissions': [('can_verify_reports', 'Can verify damage reports')],
            },
        ),
    ]
