# Generated by Django 4.2.7 on 2025-08-05 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_type', models.CharField(choices=[('flood', 'Flood Damage'), ('drought', 'Drought Damage'), ('storm', 'Storm Damage'), ('pest', 'Pest Infestation'), ('disease', 'Plant Disease'), ('frost', 'Frost Damage'), ('hail', 'Hail Damage'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('minor', 'Minor (0-25% damage)'), ('moderate', 'Moderate (26-50% damage)'), ('major', 'Major (51-75% damage)'), ('severe', 'Severe (76-100% damage)')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estimated_loss_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estimated_financial_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_occurred', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=15)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='farms.farm')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DamagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='damage_photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('damage_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='damage_reports.damagereport')),
            ],
        ),
    ]
