# Generated by Django 5.2.4 on 2025-07-17 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('pressure', models.FloatField()),
                ('conditions', models.CharField(max_length=100)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('is_forecast', models.BooleanField(default=False)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='farms.farm')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
